config/routes.rb
Apollo::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :layers
  resources :users
  resources :sessions
  resources :password_resets
  resources :subscriptions
    
  get "posts/near"

  resources :feeds, :except => [ :create, :destroy ] do
    member do
      get 'fetch'
    end
  end

  match '/fetch_all' => 'feeds#fetch_all', :as => :fetch_all

  root :to => 'layers#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
  has_many :subscriptions
  has_many :layers, :through => :subscriptions, :uniq => true
  attr_accessible :title, :url, :description, :generator, :last_fetched, :feed_url
  attr_accessor :new_layer_id # non model attribute used when creating new feeds from within a layer

  validates_format_of :feed_url, :with => URI::regexp(%w(http https)), :message => "must be a valid URL"
  
  after_create  :fetch
  
  def self.fetch_all
    Feed.all.each { |f| f.delay.fetch }
  end

  # Fetch and parse feed contents from web
  def fetch
    puts "Fetching feed: #{self.feed_url}"
    Feedzirra::Feed.add_common_feed_entry_element('georss:point', :as => :point)
    Feedzirra::Feed.add_common_feed_entry_element('geo:lat', :as => :geo_lat)
    Feedzirra::Feed.add_common_feed_entry_element('geo:long', :as => :geo_long)
    Feedzirra::Feed.add_common_feed_element('generator', :as => :generator)

    feed = Feedzirra::Feed.fetch_and_parse(self.feed_url)

    self.update_attributes(
      :title =>         feed.title,
      :url =>           feed.url,
      :description =>   feed.description,
      :generator =>     feed.generator,
      :last_fetched =>  DateTime.now
    )

    feed.entries.each do |e|
    
      if e.geo_lat && e.geo_long
        latlon = [e.geo_lat, e.geo_long]
      elsif e.point
        latlon = e.point.split(' ')
      else
        next
      end
      
      attrs = {
        :title =>     e.title,
        :url =>       e.url,
        :author =>    e.author,
        :summary =>   e.summary,
        :content =>   e.content,
        :published => e.published,
        :guid =>      e.id,
        :lon =>       latlon[1].to_f,
        :lat =>       latlon[0].to_f
      }
      
      # Create a new post or update an existing one
      post = Post.find_or_initialize_by_url(e.url)
      post.feed = self
      post.assign_attributes(attrs)
      post.save
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :require_login
    
  # GET /feeds
  # GET /feeds.json
  def index
    @feed = Feed.new
    @feeds = Feed.all :order => :title
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])
    @posts = @feed.posts.order("published desc").paginate(:page => params[:page], :per_page => 20)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # Feeds are created through the Subscriptions controller

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed updated OK' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # Feeds are never deleted. They're always retained in the DB.

  def fetch
    @feed = Feed.find(params[:id])
    @feed.fetch
    redirect_to :back, notice: 'Feed fetched OK'
  end
  
  def fetch_all
    Feed.fetch_all
    redirect_to :back, notice: 'All feeds fetched OK'
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  %h2 Add a feed

  -if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "URL"
    = f.text_field :feed_url, :size => 120
    = f.submit 'Save', :id => 'submit'
  .actions

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form'

= link_to 'Show', @feed
\|
= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
%h1 Apollo

#new_feed
  = render 'form'

%p= link_to "Fetch all", :fetch_all, :class => "button"

%table
  %tr
    %th
    %th Posts
    %th Fetched
    %th
    %th
    %th

  - @feeds.each do |f|
    %tr
      %td
        .feed_title
          = link_to f.title, f
      %td.right= f.posts.count
      %td
        - if f.last_fetched.nil?
          never
        - else
          = (time_ago_in_words(f.last_fetched) + " ago").gsub(/ +/, "&nbsp;").html_safe
      %td= link_to "Fetch", fetch_feed_url(f), :class => "button"
      %td= link_to 'Edit', edit_feed_path(f), :class => "button"
      %td= link_to 'Delete', f, :confirm => "Delete #{f.title} and all its posts?", :method => :delete, :class => "button"

  %tr
    %td
    %td.right= Post.count
    %td
    %td
    %td
    %td

app/views/feeds/new.html.haml
%h1 New feed

= render 'form'

= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
%h1= link_to @feed.title, @feed.url

%p= @feed.description

%p
  = link_to "Fetch", fetch_feed_url(@feed), :class => "button"
  &nbsp;
  %a.button{ :href => "https://validator.w3.org/feed/check.cgi?url=#{@feed.feed_url}"}<
    Validate
  &nbsp;
  = link_to 'Edit', edit_feed_path(@feed), :class => "button"

%p
  = pluralize(@feed.posts.count, "post") 

%p
  = link_to @feed.feed_url, @feed.feed_url

%p
  - if @feed.last_fetched.nil?
    This feed has never been fetched
  - else
    Last fetched 
    = time_ago_in_words @feed.last_fetched
    ago

%table#feed
  - @posts.each do |p|
    %tr
      %td= link_to p.title, p.url
      %td= link_to "Map", "https://maps.google.co.uk/maps?q=%s,%s&hl=en&z=18" % [ p.lat, p.lon ], :target => "_blank"
      %td
        - unless p.published.nil?
          = p.published.strftime("%d %b %Y %H:%M")

= will_paginate @posts