config/routes.rb
Apollo::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :layers
  resources :users
  resources :sessions
  resources :password_resets
  resources :subscriptions
    
  get "posts/near"

  resources :feeds, :except => [ :create, :destroy ] do
    member do
      get 'fetch'
    end
  end

  match '/fetch_all' => 'feeds#fetch_all', :as => :fetch_all

  root :to => 'layers#index'

end

app/models/layer.rb
class Layer < ActiveRecord::Base
  has_many :subscriptions
  has_many :feeds, :through => :subscriptions, :uniq => true

  attr_accessible :name, :icon_url

  # Unique name for Layar layer
  def layar_name
  	"apollo" + self.name.strip.downcase.gsub(/[^a-z0-9]/, '')
  end
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  before_filter :require_login
  
  # GET /layers
  # GET /layers.json
  def index
    @layers = Layer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @layers }
    end
  end

  # GET /layers/1
  # GET /layers/1.json
  def show
    @layer = Layer.find(params[:id])
    @subscription = Subscription.new(:layer_id => @layer.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @layer }
    end
  end

  # GET /layers/new
  # GET /layers/new.json
  def new
    @layer = Layer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @layer }
    end
  end

  # GET /layers/1/edit
  def edit
    @layer = Layer.find(params[:id])
  end

  # POST /layers
  # POST /layers.json
  def create
    @layer = Layer.new(params[:layer])

    respond_to do |format|
      if @layer.save
        format.html { redirect_to @layer, notice: 'Layer was successfully created.' }
        format.json { render json: @layer, status: :created, location: @layer }
      else
        format.html { render action: "new" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /layers/1
  # PUT /layers/1.json
  def update
    @layer = Layer.find(params[:id])

    respond_to do |format|
      if @layer.update_attributes(params[:layer])
        format.html { redirect_to @layer, notice: 'Layer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1
  # DELETE /layers/1.json
  def destroy
    @layer = Layer.find(params[:id])
    @layer.destroy

    respond_to do |format|
      format.html { redirect_to layers_url }
      format.json { head :no_content }
    end
  end

  # DELETE /layers/1/delete_feed
  # This only deletes the relation between the layer and the feed. The feed (and its posts) are retained.
  # Currently there's no way for the user to actually delete a feed completely.
  def delete_feed
    @layer = Layer.find(params[:id])
    @feed = Feed.find(params[:feed_id])
    @layer.feeds.delete(@feed)
    redirect_to @layer, notice: "Deleted feed #{@feed.title} from this layer"
  end
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_form.html.haml
= form_for @layer do |f|
  - if @layer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@layer.errors.count, "error")} prohibited this layer from being saved:"
      %ul
        - @layer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    %br
    = f.text_field :name
  %br
  .field
    = f.label "Icon URL (optional; maximum 100px wide by 75px high)"
    %br
    = f.text_field :icon_url, :size => 60
  %br
  .actions
    = f.submit 'Save'

app/views/layers/edit.html.haml
%h1 Editing layer

= render 'form'

= link_to 'Show', @layer
\|
= link_to 'Back', layers_path

app/views/layers/index.html.haml
%h1 Layers

= link_to 'New Layer', new_layer_path, :class => 'button'

%table
  - @layers.each do |layer|
    %tr
      %td= link_to layer.name, layer
      %td= link_to 'Edit', edit_layer_path(layer), :class => 'button'
      %td= link_to 'Delete', layer, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'button'

app/views/layers/new.html.haml
%h1 New layer

= render 'form'

= link_to 'Back', layers_path

app/views/layers/show.html.haml
%h1
  Layer: 
  = @layer.name

%p
  API URL:
  = "#{request.protocol}#{request.host_with_port}/posts/near.layar?layer_id=#{@layer.id}"
  %br
  Layar layer name:
  = @layer.layar_name

%h2 Feeds

#new_feed
  = render 'subscriptions/form'

%p= link_to "Fetch all", :fetch_all, :class => "button"

%table
  %tr
    %th
    %th Posts
    %th Fetched
    %th
    %th
    %th
  - @layer_posts = 0
  - @layer.subscriptions.each do |s|
    - @layer_posts += s.feed.posts.count
    %tr
      %td
        .feed_title
          = link_to s.feed.title, s.feed
      %td.right= s.feed.posts.count
      %td
        - if s.feed.last_fetched.nil?
          never
        - else
          = (time_ago_in_words(s.feed.last_fetched) + " ago").gsub(/ +/, "&nbsp;").html_safe
      %td= link_to "Fetch", fetch_feed_url(s.feed), :class => "button"
      %td= link_to 'Edit', edit_feed_path(s.feed), :class => "button"
      %td= link_to 'Delete', s, :confirm => "Delete #{s.feed.title}?", :method => :delete, :class => "button"
      %td
        %a.button{ :href => edit_subscription_path(s) }
          Edit&nbsp;icon
      %td
        - unless s.icon_url.blank?
          = image_tag s.icon_url
        - else
          &nbsp;
  %tr
    %td
    %td.right= @layer_posts
    %td
    %td
    %td
    %td

= link_to 'Edit', edit_layer_path(@layer)
\|
= link_to 'Back', layers_path